### ISSUE TITLE
fails to load example project

### ISSUE THREAD

**Issue by vickerse1** [calebweinreb/SNUB#2]
running from anaconda prompt in Windows 10, gives this error (Buffer dtype mismatch, expected 'const int64_t' but got 'long':

-----------
Traceback (most recent call last):
  File "c:\users\mccormick lab\documents\python\snub\snub\gui\main.py", line 362, in open
    self.load_project(project_dir)
  File "c:\users\mccormick lab\documents\python\snub\snub\gui\main.py", line 381, in load_project
    project_tab = ProjectTab(project_directory)
  File "c:\users\mccormick lab\documents\python\snub\snub\gui\main.py", line 107, in __init__
    self.update_current_time(self.current_time)
  File "c:\users\mccormick lab\documents\python\snub\snub\gui\main.py", line 251, in update_current_time
    self.panelStack.update_current_time(current_time)
  File "c:\users\mccormick lab\documents\python\snub\snub\gui\stacks\panel.py", line 52, in update_current_time
    panel.update_current_time(t)
  File "c:\users\mccormick lab\documents\python\snub\snub\gui\panels\scatter.py", line 130, in update_current_time
    nodes,time_indexes = self.interval_index.intervals_containing(times)
  File "c:\users\mccormick lab\documents\python\snub\snub\gui\utils\interval.py", line 65, in intervals_containing
    query_ixs,ref_ixs = self.all_containments_both(self.intervals, query_locations)
  File "c:\users\mccormick lab\documents\python\snub\snub\gui\utils\interval.py", line 89, in all_containments_both
    return ncls.all_containments_both(query_locations,query_locations, np.arange(len(query_locations)))
  File "ncls/src/ncls32.pyx", line 631, in ncls.src.ncls32.NCLS32.all_containments_both
    cpdef all_containments_both(self, const int32_t [::1] starts, const int32_t [::1] ends, const int64_t [::1] indexes):
ValueError: Buffer dtype mismatch, expected 'const int64_t' but got 'long'
Traceback (most recent call last):
  File "c:\users\mccormick lab\documents\python\snub\snub\gui\main.py", line 339, in change_layout_mode
    current_tab.change_layout_mode(layout_mode)
AttributeError: 'NoneType' object has no attribute 'change_layout_mode'
Traceback (most recent call last):
  File "c:\users\mccormick lab\documents\python\snub\snub\gui\main.py", line 362, in open
    self.load_project(project_dir)
  File "c:\users\mccormick lab\documents\python\snub\snub\gui\main.py", line 381, in load_project
    project_tab = ProjectTab(project_directory)
  File "c:\users\mccormick lab\documents\python\snub\snub\gui\main.py", line 107, in __init__
    self.update_current_time(self.current_time)
  File "c:\users\mccormick lab\documents\python\snub\snub\gui\main.py", line 251, in update_current_time
    self.panelStack.update_current_time(current_time)
  File "c:\users\mccormick lab\documents\python\snub\snub\gui\stacks\panel.py", line 52, in update_current_time
    panel.update_current_time(t)
  File "c:\users\mccormick lab\documents\python\snub\snub\gui\panels\scatter.py", line 130, in update_current_time
    nodes,time_indexes = self.interval_index.intervals_containing(times)
  File "c:\users\mccormick lab\documents\python\snub\snub\gui\utils\interval.py", line 65, in intervals_containing
    query_ixs,ref_ixs = self.all_containments_both(self.intervals, query_locations)
  File "c:\users\mccormick lab\documents\python\snub\snub\gui\utils\interval.py", line 89, in all_containments_both
    return ncls.all_containments_both(query_locations,query_locations, np.arange(len(query_locations)))
  File "ncls/src/ncls32.pyx", line 631, in ncls.src.ncls32.NCLS32.all_containments_both
    cpdef all_containments_both(self, const int32_t [::1] starts, const int32_t [::1] ends, const int64_t [::1] indexes):
ValueError: Buffer dtype mismatch, expected 'const int64_t' but got 'long'
---------------

Thanks,

Evan

**Comment by vickerse1** [comment]
Python 3.8.13

**Comment by calebweinreb** [comment]
Thanks for the post! We've previously had some issues with running NCLS on windows. I added a [line ](https://github.com/calebweinreb/SNUB/blob/f542caa0575807a4d61261168dd9bce48344dac9/snub/gui/utils/interval.py#L76) that should patch this. Can you try running again with the latest commit? If that doesn't work, uninstalling NCLS should get rid of the issue.
